language: swift
osx_image: xcode8.3
script:
- swift package update
- xcodebuild test -project Ditto.xcodeproj -scheme Ditto -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1'

