language: swift
osx_image: xcode8.3
script:
- xcodebuild test -project Ditto.xcodeproj -scheme "Ditto-iOS" -sdk "iphonesimulator" -destination "OS=10.3.1,name=iPhone 7"
- xcodebuild test -project Ditto.xcodeproj -scheme "Ditto-macOS" -sdk "macosx" -destination "arch=x86_64"
- xcodebuild -project Ditto.xcodeproj -scheme "Ditto-watchOS" -sdk "watchsimulator" -destination "OS=3.2,name=Apple Watch - 42mm"
- xcodebuild test -project Ditto.xcodeproj -scheme "Ditto-tvOS" -sdk "appletvsimulator" -destination "OS=10.0,name=Apple TV 1080p"

